spring:
  application:
    name: driver-service
  data:
    mongodb:
      uri: ${DRIVER_MONGODB_URI}

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

