spring:
  application:
    name: fare-payment-service
  data:
    mongodb:
      uri: ${PAYMENT_MONGODB_URI}

server:
  port: 8084

fare:
  base-fare: 200.00
  rate-per-km: 50.00

springdoc:
  swagger-ui:
    path: /swagger-ui.html

