spring:
  application:
    name: ride-service
  data:
    mongodb:
      uri: ${RIDE_MONGODB_URI}

server:
  port: 8083

driver-service:
  url: ${DRIVER_SERVICE_URL:http://localhost:8082}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

